version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory:  /home/circleci/innovation-lab-booking
    steps:
      - checkout

      - run:
          name: Install Python and AWS-CLI
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install -y python-pip python-dev 
            sudo pip install awscli

      - run: 
          name: Sync to S3 bucket
          command: |
            aws s3 cp $CIRCLE_WORKING_DIRECTORY/labRequests.js s3://innovation-lab.cz/src/labRequests.js --region eu-central-1